version: 2.1

orbs:
  maven: circleci/maven@1.1.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - save_cache:
            paths:
              - ~/.m2
            key: v1-dependencies-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target/TomcatEmbedded.war
      - store_artifacts:
          path: target/dependency/webapp-runner.jar
  unit-tests:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml file
            - v1-dependencies- # fallback in case previous cache key is not found
      - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/test-results/junit
  deploy:
    docker:
      - image: circleci/node:latest #node:12-alpine
    steps:
      - run: "echo deployed"
  up9-integration-test:
    docker:
      - image: gcr.io/up9-docker-hub/circleci/cimg/up9:latest #circleci/node:latest #node:12-alpine
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run: 
          name: "[UP9] Install latest CLI"
          command: sudo npm i -g up9
      - run: 
          name: "[UP9] Authenticate"
          command: up9 auth:login --client-id=$UP9_CLIENT_ID --client-secret=$UP9_CLIENT_SECRET --env=$UP9_ENV
      - run:
          name: "[UP9] Environment setup"
          command: |
            mkdir -p ~/test-results/up9
            cd ~/test-results/up9
            tab="  "
            echo "services:" > services.yaml
            echo "$tab"TARGET_CARTS: >> services.yaml
            echo "$tab""$tab"remoteUrl: http://google.com >> services.yaml
      # mkdir -p ~/.config/up9/tests/$UP9_WORKSPACE
      # - run:
      #     name: "[UP9] Fetch containers"
      #     command: "docker pull gcr.io/up9-docker-hub/test-runner/develop:latest"
      - run: 
          name: "[UP9] Fetch and run tests"
          command: |
            cd ~/test-results/up9
            up9 test:run-local $UP9_WORKSPACE $UP9_SUBSYSTEM --services-config-file=services.yaml --junit
            cat junit.*.xml > up9-results.xml
          #awk 'NR==3 {print "<properties><property name=\"up9-link\" value=\"https://up9.app\"/></properties>"} 1' junit.*.xml > up9-results.xml
      - store_test_results:
          path: ~/test-results/up9
      - store_artifacts:
          path: ~/test-results/up9
workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - deploy:
          requires:
            - build
            - unit-tests
      - up9-integration-test:
          requires:
            - unit-tests
            - deploy